export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAILURE = 'PRODUCT_LIST_FAILURE';
export const CLEAR_PRODUCT_LIST_DATA= 'CLEAR_PRODUCT_LIST_DATA';
export const PRODUCT_UPDATE_REQUEST= 'PRODUCT_UPDATE_REQUEST';
export const PRODUCT_UPDATE_SUCCESS= 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAILURE= 'PRODUCT_UPDATE_FAILURE';
export const CLEAR_UPDATE_UPDATE_DATA = 'CLEAR_UPDATE_UPDATE_DATA';
