export const DEPARTMENT_LIST_REQUEST='DEPARTMENT_LIST_REQUEST';
export const DEPARTMENT_LIST_SUCCESS= 'DEPARTMENT_LIST_SUCCESS';
export const DEPARTMENT_LIST_FAILURE= 'DEPARTMENT_LIST_FAILURE';
export const CLEAR_DEPARTMENT_LIST_DATA='CLEAR_DEPARTMENT_LIST_DATA';
export const DEPARTMENT_ADD_REQUEST= 'DEPARTMENT_ADD_REQUEST';
export const DEPARTMENT_ADD_SUCCESS = 'DEPARTMENT_ADD_SUCCESS';
export const DEPARTMENT_ADD_FAILURE = 'DEPARTMENT_ADD_FAILURE';
export const CLEAR_DEPARTMENT_ADD_DATA = 'CLEAR_DEPARTMENT_ADD_DATA';
export const DEPARTMENT_DEL_REQUEST= 'DEPARTMENT_DEL_REQUEST';
export const DEPARTMENT_DEL_SUCCESS = 'DEPARTMENT_DEL_SUCCESS';
export const DEPARTMENT_DEL_FAILURE = 'DEPARTMENT_DEL_FAILURE';
export const CLEAR_DEPARTMENT_DEL_DATA = 'CLEAR_DEPARTMENT_DEL_DATA';
export const DEPARTMENT_UPDATE_REQUEST= 'DEPARTMENT_UPDATE_REQUEST';
export const DEPARTMENT_UPDATE_SUCCESS= 'DEPARTMENT_UPDATE_SUCCESS';
export const DEPARTMENT_UPDATE_FAILURE= 'DEPARTMENT_UPDATE_FAILURE';
export const CLEAR_DEPARTMENT_UPDATE_DATA= 'CLEAR_DEPARTMENT_UPDATE_DATA';
export const DEPARTMENT_DETAILSBYID_REQUEST= 'DEPARTMENT_DETAILSBYID_REQUEST';
export const DEPARTMENT_DETAILSBYID_SUCESS= 'DEPARTMENT_DETAILSBYID_SUCESS';
export const DEPARTMENT_DETAILSBYID_FAILURE= 'DEPARTMENT_DETAILSBYID_FAILURE';
export const CLEAR_DEPARTMENT_DETAILSBYID_DATA = 'CLEAR_DEPARTMENT_DETAILSBYID_DATA';
export const DEPARTMENT_DD_SUCCESS = 'DEPARTMENT_DD_SUCCESS';
export const DEPARTMENT_DD_FAILURE = 'DEPARTMENT_DD_FAILURE';
export const DEPARTMENT_DD_REQUEST = 'DEPARTMENT_DD_REQUEST';
export const CLEAR_DEPARTMENT_DD_REQUEST="CLEAR_DEPARTMENT_DD_REQUEST"


















